### ISSUE TITLE
Figure properties triggers error

### ISSUE THREAD

**Issue by grgdll** [BoldingBruggeman/pyncview#14]
When trying to change the figure properties a pop up windows opens with the error below. Even if I close the error windows it will re-open until I close the property window.

Traceback (most recent call last):
  File "/storage/sire/users/grg/miniconda3/envs/fabmos/lib/python3.11/site-packages/xmlstore/gui_qt4.py", line 910, in paint
    editorclass.displayValue(self,painter,option,index)
  File "/storage/sire/users/grg/miniconda3/envs/fabmos/lib/python3.11/site-packages/xmlstore/gui_qt4.py", line 839, in displayValue
    qPixMap = cls.getPixMap(value,cls.width,cls.height,dpi)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/sire/users/grg/miniconda3/envs/fabmos/lib/python3.11/site-packages/xmlstore/gui_qt4.py", line 825, in getPixMap
    qPixMap = cls.createPixMap(value,width,height,dpi)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/sire/users/grg/miniconda3/envs/fabmos/lib/python3.11/site-packages/xmlplot/gui_qt4.py", line 131, in createPixMap
    qImage = QtGui.QImage(stringBuffer, width, height, QtGui.QImage.Format_ARGB32)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: arguments did not match any overloaded call:
  QImage(): too many arguments
  QImage(size: QSize, format: QImage.Format): argument 1 has unexpected type 'memoryview'
  QImage(width: int, height: int, format: QImage.Format): argument 1 has unexpected type 'memoryview'
  QImage(data: typing.Optional[bytes], width: int, height: int, format: QImage.Format): argument 2 has unexpected type 'float'
  QImage(data: typing.Optional[PyQt5.sip.voidptr], width: int, height: int, format: QImage.Format): argument 2 has unexpected type 'float'
  QImage(data: typing.Optional[bytes], width: int, height: int, bytesPerLine: int, format: QImage.Format): argument 2 has unexpected type 'float'
  QImage(data: typing.Optional[PyQt5.sip.voidptr], width: int, height: int, bytesPerLine: int, format: QImage.Format): argument 2 has unexpected type 'float'
  QImage(xpm: List[str]): argument 1 has unexpected type 'memoryview'
  QImage(fileName: str, format: typing.Optional[str] = None): argument 1 has unexpected type 'memoryview'
  QImage(a0: QImage): argument 1 has unexpected type 'memoryview'
  QImage(variant: Any): too many arguments
Traceback (most recent call last):
  File "/storage/sire/users/grg/miniconda3/envs/fabmos/lib/python3.11/site-packages/xmlstore/gui_qt4.py", line 910, in paint
    editorclass.displayValue(self,painter,option,index)
  File "/storage/sire/users/grg/miniconda3/envs/fabmos/lib/python3.11/site-packages/xmlstore/gui_qt4.py", line 839, in displayValue
    qPixMap = cls.getPixMap(value,cls.width,cls.height,dpi)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/sire/users/grg/miniconda3/envs/fabmos/lib/python3.11/site-packages/xmlstore/gui_qt4.py", line 825, in getPixMap
    qPixMap = cls.createPixMap(value,width,height,dpi)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/sire/users/grg/miniconda3/envs/fabmos/lib/python3.11/site-packages/xmlplot/gui_qt4.py", line 131, in createPixMap
    qImage = QtGui.QImage(stringBuffer, width, height, QtGui.QImage.Format_ARGB32)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: arguments did not match any overloaded call:
  QImage(): too many arguments
  QImage(size: QSize, format: QImage.Format): argument 1 has unexpected type 'memoryview'
  QImage(width: int, height: int, format: QImage.Format): argument 1 has unexpected type 'memoryview'
  QImage(data: typing.Optional[bytes], width: int, height: int, format: QImage.Format): argument 2 has unexpected type 'float'
  QImage(data: typing.Optional[PyQt5.sip.voidptr], width: int, height: int, format: QImage.Format): argument 2 has unexpected type 'float'
  QImage(data: typing.Optional[bytes], width: int, height: int, bytesPerLine: int, format: QImage.Format): argument 2 has unexpected type 'float'
  QImage(data: typing.Optional[PyQt5.sip.voidptr], width: int, height: int, bytesPerLine: int, format: QImage.Format): argument 2 has unexpected type 'float'
  QImage(xpm: List[str]): argument 1 has unexpected type 'memoryview'
  QImage(fileName: str, format: typing.Optional[str] = None): argument 1 has unexpected type 'memoryview'
  QImage(a0: QImage): argument 1 has unexpected type 'memoryview'
  QImage(variant: Any): too many arguments
Traceback (most recent call last):
  File "/storage/sire/users/grg/miniconda3/envs/fabmos/lib/python3.11/site-packages/xmlstore/gui_qt4.py", line 910, in paint
    editorclass.displayValue(self,painter,option,index)
  File "/storage/sire/users/grg/miniconda3/envs/fabmos/lib/python3.11/site-packages/xmlstore/gui_qt4.py", line 839, in displayValue
    qPixMap = cls.getPixMap(value,cls.width,cls.height,dpi)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/sire/users/grg/miniconda3/envs/fabmos/lib/python3.11/site-packages/xmlstore/gui_qt4.py", line 825, in getPixMap
    qPixMap = cls.createPixMap(value,width,height,dpi)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/sire/users/grg/miniconda3/envs/fabmos/lib/python3.11/site-packages/xmlplot/gui_qt4.py", line 131, in createPixMap
    qImage = QtGui.QImage(stringBuffer, width, height, QtGui.QImage.Format_ARGB32)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: arguments did not match any overloaded call:
  QImage(): too many arguments
  QImage(size: QSize, format: QImage.Format): argument 1 has unexpected type 'memoryview'
  QImage(width: int, height: int, format: QImage.Format): argument 1 has unexpected type 'memoryview'
  QImage(data: typing.Optional[bytes], width: int, height: int, format: QImage.Format): argument 2 has unexpected type 'float'
  QImage(data: typing.Optional[PyQt5.sip.voidptr], width: int, height: int, format: QImage.Format): argument 2 has unexpected type 'float'
  QImage(data: typing.Optional[bytes], width: int, height: int, bytesPerLine: int, format: QImage.Format): argument 2 has unexpected type 'float'
  QImage(data: typing.Optional[PyQt5.sip.voidptr], width: int, height: int, bytesPerLine: int, format: QImage.Format): argument 2 has unexpected type 'float'
  QImage(xpm: List[str]): argument 1 has unexpected type 'memoryview'
  QImage(fileName: str, format: typing.Optional[str] = None): argument 1 has unexpected type 'memoryview'
  QImage(a0: QImage): argument 1 has unexpected type 'memoryview'
  QImage(variant: Any): too many arguments
Traceback (most recent call last):
  File "/storage/sire/users/grg/miniconda3/envs/fabmos/lib/python3.11/site-packages/xmlstore/gui_qt4.py", line 910, in paint
    editorclass.displayValue(self,painter,option,index)
  File "/storage/sire/users/grg/miniconda3/envs/fabmos/lib/python3.11/site-packages/xmlstore/gui_qt4.py", line 839, in displayValue
    qPixMap = cls.getPixMap(value,cls.width,cls.height,dpi)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/sire/users/grg/miniconda3/envs/fabmos/lib/python3.11/site-packages/xmlstore/gui_qt4.py", line 825, in getPixMap
    qPixMap = cls.createPixMap(value,width,height,dpi)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/sire/users/grg/miniconda3/envs/fabmos/lib/python3.11/site-packages/xmlplot/gui_qt4.py", line 131, in createPixMap
    qImage = QtGui.QImage(stringBuffer, width, height, QtGui.QImage.Format_ARGB32)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: arguments did not match any overloaded call:
  QImage(): too many arguments
  QImage(size: QSize, format: QImage.Format): argument 1 has unexpected type 'memoryview'
  QImage(width: int, height: int, format: QImage.Format): argument 1 has unexpected type 'memoryview'
  QImage(data: typing.Optional[bytes], width: int, height: int, format: QImage.Format): argument 2 has unexpected type 'float'
  QImage(data: typing.Optional[PyQt5.sip.voidptr], width: int, height: int, format: QImage.Format): argument 2 has unexpected type 'float'
  QImage(data: typing.Optional[bytes], width: int, height: int, bytesPerLine: int, format: QImage.Format): argument 2 has unexpected type 'float'
  QImage(data: typing.Optional[PyQt5.sip.voidptr], width: int, height: int, bytesPerLine: int, format: QImage.Format): argument 2 has unexpected type 'float'
  QImage(xpm: List[str]): argument 1 has unexpected type 'memoryview'
  QImage(fileName: str, format: typing.Optional[str] = None): argument 1 has unexpected type 'memoryview'
  QImage(a0: QImage): argument 1 has unexpected type 'memoryview'
  QImage(variant: Any): too many arguments
Traceback (most recent call last):
  File "/storage/sire/users/grg/miniconda3/envs/fabmos/lib/python3.11/site-packages/xmlstore/gui_qt4.py", line 910, in paint
    editorclass.displayValue(self,painter,option,index)
  File "/storage/sire/users/grg/miniconda3/envs/fabmos/lib/python3.11/site-packages/xmlstore/gui_qt4.py", line 839, in displayValue
    qPixMap = cls.getPixMap(value,cls.width,cls.height,dpi)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/sire/users/grg/miniconda3/envs/fabmos/lib/python3.11/site-packages/xmlstore/gui_qt4.py", line 825, in getPixMap
    qPixMap = cls.createPixMap(value,width,height,dpi)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/sire/users/grg/miniconda3/envs/fabmos/lib/python3.11/site-packages/xmlplot/gui_qt4.py", line 131, in createPixMap
    qImage = QtGui.QImage(stringBuffer, width, height, QtGui.QImage.Format_ARGB32)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: arguments did not match any overloaded call:
  QImage(): too many arguments
  QImage(size: QSize, format: QImage.Format): argument 1 has unexpected type 'memoryview'
  QImage(width: int, height: int, format: QImage.Format): argument 1 has unexpected type 'memoryview'
  QImage(data: typing.Optional[bytes], width: int, height: int, format: QImage.Format): argument 2 has unexpected type 'float'
  QImage(data: typing.Optional[PyQt5.sip.voidptr], width: int, height: int, format: QImage.Format): argument 2 has unexpected type 'float'
  QImage(data: typing.Optional[bytes], width: int, height: int, bytesPerLine: int, format: QImage.Format): argument 2 has unexpected type 'float'
  QImage(data: typing.Optional[PyQt5.sip.voidptr], width: int, height: int, bytesPerLine: int, format: QImage.Format): argument 2 has unexpected type 'float'
  QImage(xpm: List[str]): argument 1 has unexpected type 'memoryview'
  QImage(fileName: str, format: typing.Optional[str] = None): argument 1 has unexpected type 'memoryview'
  QImage(a0: QImage): argument 1 has unexpected type 'memoryview'
  QImage(variant: Any): too many arguments
Traceback (most recent call last):
  File "/storage/sire/users/grg/miniconda3/envs/fabmos/lib/python3.11/site-packages/xmlstore/gui_qt4.py", line 910, in paint
    editorclass.displayValue(self,painter,option,index)
  File "/storage/sire/users/grg/miniconda3/envs/fabmos/lib/python3.11/site-packages/xmlstore/gui_qt4.py", line 839, in displayValue
    qPixMap = cls.getPixMap(value,cls.width,cls.height,dpi)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/sire/users/grg/miniconda3/envs/fabmos/lib/python3.11/site-packages/xmlstore/gui_qt4.py", line 825, in getPixMap
    qPixMap = cls.createPixMap(value,width,height,dpi)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/sire/users/grg/miniconda3/envs/fabmos/lib/python3.11/site-packages/xmlplot/gui_qt4.py", line 131, in createPixMap
    qImage = QtGui.QImage(stringBuffer, width, height, QtGui.QImage.Format_ARGB32)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: arguments did not match any overloaded call:
  QImage(): too many arguments
  QImage(size: QSize, format: QImage.Format): argument 1 has unexpected type 'memoryview'
  QImage(width: int, height: int, format: QImage.Format): argument 1 has unexpected type 'memoryview'
  QImage(data: typing.Optional[bytes], width: int, height: int, format: QImage.Format): argument 2 has unexpected type 'float'
  QImage(data: typing.Optional[PyQt5.sip.voidptr], width: int, height: int, format: QImage.Format): argument 2 has unexpected type 'float'
  QImage(data: typing.Optional[bytes], width: int, height: int, bytesPerLine: int, format: QImage.Format): argument 2 has unexpected type 'float'
  QImage(data: typing.Optional[PyQt5.sip.voidptr], width: int, height: int, bytesPerLine: int, format: QImage.Format): argument 2 has unexpected type 'float'
  QImage(xpm: List[str]): argument 1 has unexpected type 'memoryview'
  QImage(fileName: str, format: typing.Optional[str] = None): argument 1 has unexpected type 'memoryview'
  QImage(a0: QImage): argument 1 has unexpected type 'memoryview'
  QImage(variant: Any): too many arguments
Traceback (most recent call last):
  File "/storage/sire/users/grg/miniconda3/envs/fabmos/lib/python3.11/site-packages/xmlstore/gui_qt4.py", line 910, in paint
    editorclass.displayValue(self,painter,option,index)
  File "/storage/sire/users/grg/miniconda3/envs/fabmos/lib/python3.11/site-packages/xmlstore/gui_qt4.py", line 839, in displayValue
    qPixMap = cls.getPixMap(value,cls.width,cls.height,dpi)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/sire/users/grg/miniconda3/envs/fabmos/lib/python3.11/site-packages/xmlstore/gui_qt4.py", line 825, in getPixMap
    qPixMap = cls.createPixMap(value,width,height,dpi)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/sire/users/grg/miniconda3/envs/fabmos/lib/python3.11/site-packages/xmlplot/gui_qt4.py", line 131, in createPixMap
    qImage = QtGui.QImage(stringBuffer, width, height, QtGui.QImage.Format_ARGB32)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: arguments did not match any overloaded call:
  QImage(): too many arguments
  QImage(size: QSize, format: QImage.Format): argument 1 has unexpected type 'memoryview'
  QImage(width: int, height: int, format: QImage.Format): argument 1 has unexpected type 'memoryview'
  QImage(data: typing.Optional[bytes], width: int, height: int, format: QImage.Format): argument 2 has unexpected type 'float'
  QImage(data: typing.Optional[PyQt5.sip.voidptr], width: int, height: int, format: QImage.Format): argument 2 has unexpected type 'float'
  QImage(data: typing.Optional[bytes], width: int, height: int, bytesPerLine: int, format: QImage.Format): argument 2 has unexpected type 'float'
  QImage(data: typing.Optional[PyQt5.sip.voidptr], width: int, height: int, bytesPerLine: int, format: QImage.Format): argument 2 has unexpected type 'float'
  QImage(xpm: List[str]): argument 1 has unexpected type 'memoryview'
  QImage(fileName: str, format: typing.Optional[str] = None): argument 1 has unexpected type 'memoryview'
  QImage(a0: QImage): argument 1 has unexpected type 'memoryview'
  QImage(variant: Any): too many arguments
Traceback (most recent call last):
  File "/storage/sire/users/grg/miniconda3/envs/fabmos/lib/python3.11/site-packages/xmlstore/gui_qt4.py", line 910, in paint
    editorclass.displayValue(self,painter,option,index)
  File "/storage/sire/users/grg/miniconda3/envs/fabmos/lib/python3.11/site-packages/xmlstore/gui_qt4.py", line 839, in displayValue
    qPixMap = cls.getPixMap(value,cls.width,cls.height,dpi)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/sire/users/grg/miniconda3/envs/fabmos/lib/python3.11/site-packages/xmlstore/gui_qt4.py", line 825, in getPixMap
    qPixMap = cls.createPixMap(value,width,height,dpi)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/sire/users/grg/miniconda3/envs/fabmos/lib/python3.11/site-packages/xmlplot/gui_qt4.py", line 131, in createPixMap
    qImage = QtGui.QImage(stringBuffer, width, height, QtGui.QImage.Format_ARGB32)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: arguments did not match any overloaded call:
  QImage(): too many arguments
  QImage(size: QSize, format: QImage.Format): argument 1 has unexpected type 'memoryview'
  QImage(width: int, height: int, format: QImage.Format): argument 1 has unexpected type 'memoryview'
  QImage(data: typing.Optional[bytes], width: int, height: int, format: QImage.Format): argument 2 has unexpected type 'float'
  QImage(data: typing.Optional[PyQt5.sip.voidptr], width: int, height: int, format: QImage.Format): argument 2 has unexpected type 'float'
  QImage(data: typing.Optional[bytes], width: int, height: int, bytesPerLine: int, format: QImage.Format): argument 2 has unexpected type 'float'
  QImage(data: typing.Optional[PyQt5.sip.voidptr], width: int, height: int, bytesPerLine: int, format: QImage.Format): argument 2 has unexpected type 'float'
  QImage(xpm: List[str]): argument 1 has unexpected type 'memoryview'
  QImage(fileName: str, format: typing.Optional[str] = None): argument 1 has unexpected type 'memoryview'
  QImage(a0: QImage): argument 1 has unexpected type 'memoryview'
  QImage(variant: Any): too many arguments
Traceback (most recent call last):
  File "/storage/sire/users/grg/miniconda3/envs/fabmos/lib/python3.11/site-packages/xmlstore/gui_qt4.py", line 910, in paint
    editorclass.displayValue(self,painter,option,index)
  File "/storage/sire/users/grg/miniconda3/envs/fabmos/lib/python3.11/site-packages/xmlstore/gui_qt4.py", line 839, in displayValue
    qPixMap = cls.getPixMap(value,cls.width,cls.height,dpi)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/sire/users/grg/miniconda3/envs/fabmos/lib/python3.11/site-packages/xmlstore/gui_qt4.py", line 825, in getPixMap
    qPixMap = cls.createPixMap(value,width,height,dpi)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/sire/users/grg/miniconda3/envs/fabmos/lib/python3.11/site-packages/xmlplot/gui_qt4.py", line 131, in createPixMap
    qImage = QtGui.QImage(stringBuffer, width, height, QtGui.QImage.Format_ARGB32)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: arguments did not match any overloaded call:
  QImage(): too many arguments
  QImage(size: QSize, format: QImage.Format): argument 1 has unexpected type 'memoryview'
  QImage(width: int, height: int, format: QImage.Format): argument 1 has unexpected type 'memoryview'
  QImage(data: typing.Optional[bytes], width: int, height: int, format: QImage.Format): argument 2 has unexpected type 'float'
  QImage(data: typing.Optional[PyQt5.sip.voidptr], width: int, height: int, format: QImage.Format): argument 2 has unexpected type 'float'
  QImage(data: typing.Optional[bytes], width: int, height: int, bytesPerLine: int, format: QImage.Format): argument 2 has unexpected type 'float'
  QImage(data: typing.Optional[PyQt5.sip.voidptr], width: int, height: int, bytesPerLine: int, format: QImage.Format): argument 2 has unexpected type 'float'
  QImage(xpm: List[str]): argument 1 has unexpected type 'memoryview'
  QImage(fileName: str, format: typing.Optional[str] = None): argument 1 has unexpected type 'memoryview'
  QImage(a0: QImage): argument 1 has unexpected type 'memoryview'
  QImage(variant: Any): too many arguments
Traceback (most recent call last):
  File "/storage/sire/users/grg/miniconda3/envs/fabmos/lib/python3.11/site-packages/xmlstore/gui_qt4.py", line 910, in paint
    editorclass.displayValue(self,painter,option,index)
  File "/storage/sire/users/grg/miniconda3/envs/fabmos/lib/python3.11/site-packages/xmlstore/gui_qt4.py", line 839, in displayValue
    qPixMap = cls.getPixMap(value,cls.width,cls.height,dpi)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/sire/users/grg/miniconda3/envs/fabmos/lib/python3.11/site-packages/xmlstore/gui_qt4.py", line 825, in getPixMap
    qPixMap = cls.createPixMap(value,width,height,dpi)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/sire/users/grg/miniconda3/envs/fabmos/lib/python3.11/site-packages/xmlplot/gui_qt4.py", line 131, in createPixMap
    qImage = QtGui.QImage(stringBuffer, width, height, QtGui.QImage.Format_ARGB32)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: arguments did not match any overloaded call:
  QImage(): too many arguments
  QImage(size: QSize, format: QImage.Format): argument 1 has unexpected type 'memoryview'
  QImage(width: int, height: int, format: QImage.Format): argument 1 has unexpected type 'memoryview'
  QImage(data: typing.Optional[bytes], width: int, height: int, format: QImage.Format): argument 2 has unexpected type 'float'
  QImage(data: typing.Optional[PyQt5.sip.voidptr], width: int, height: int, format: QImage.Format): argument 2 has unexpected type 'float'
  QImage(data: typing.Optional[bytes], width: int, height: int, bytesPerLine: int, format: QImage.Format): argument 2 has unexpected type 'float'
  QImage(data: typing.Optional[PyQt5.sip.voidptr], width: int, height: int, bytesPerLine: int, format: QImage.Format): argument 2 has unexpected type 'float'
  QImage(xpm: List[str]): argument 1 has unexpected type 'memoryview'
  QImage(fileName: str, format: typing.Optional[str] = None): argument 1 has unexpected type 'memoryview'
  QImage(a0: QImage): argument 1 has unexpected type 'memoryview'
  QImage(variant: Any): too many arguments
Traceback (most recent call last):
  File "/storage/sire/users/grg/miniconda3/envs/fabmos/lib/python3.11/site-packages/xmlstore/gui_qt4.py", line 910, in paint
    editorclass.displayValue(self,painter,option,index)
  File "/storage/sire/users/grg/miniconda3/envs/fabmos/lib/python3.11/site-packages/xmlstore/gui_qt4.py", line 839, in displayValue
    qPixMap = cls.getPixMap(value,cls.width,cls.height,dpi)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/sire/users/grg/miniconda3/envs/fabmos/lib/python3.11/site-packages/xmlstore/gui_qt4.py", line 825, in getPixMap
    qPixMap = cls.createPixMap(value,width,height,dpi)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/sire/users/grg/miniconda3/envs/fabmos/lib/python3.11/site-packages/xmlplot/gui_qt4.py", line 131, in createPixMap
    qImage = QtGui.QImage(stringBuffer, width, height, QtGui.QImage.Format_ARGB32)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: arguments did not match any overloaded call:
  QImage(): too many arguments
  QImage(size: QSize, format: QImage.Format): argument 1 has unexpected type 'memoryview'
  QImage(width: int, height: int, format: QImage.Format): argument 1 has unexpected type 'memoryview'
  QImage(data: typing.Optional[bytes], width: int, height: int, format: QImage.Format): argument 2 has unexpected type 'float'
  QImage(data: typing.Optional[PyQt5.sip.voidptr], width: int, height: int, format: QImage.Format): argument 2 has unexpected type 'float'
  QImage(data: typing.Optional[bytes], width: int, height: int, bytesPerLine: int, format: QImage.Format): argument 2 has unexpected type 'float'
  QImage(data: typing.Optional[PyQt5.sip.voidptr], width: int, height: int, bytesPerLine: int, format: QImage.Format): argument 2 has unexpected type 'float'
  QImage(xpm: List[str]): argument 1 has unexpected type 'memoryview'
  QImage(fileName: str, format: typing.Optional[str] = None): argument 1 has unexpected type 'memoryview'
  QImage(a0: QImage): argument 1 has unexpected type 'memoryview'
  QImage(variant: Any): too many arguments
Traceback (most recent call last):
  File "/storage/sire/users/grg/miniconda3/envs/fabmos/lib/python3.11/site-packages/xmlstore/gui_qt4.py", line 910, in paint
    editorclass.displayValue(self,painter,option,index)
  File "/storage/sire/users/grg/miniconda3/envs/fabmos/lib/python3.11/site-packages/xmlstore/gui_qt4.py", line 839, in displayValue
    qPixMap = cls.getPixMap(value,cls.width,cls.height,dpi)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/sire/users/grg/miniconda3/envs/fabmos/lib/python3.11/site-packages/xmlstore/gui_qt4.py", line 825, in getPixMap
    qPixMap = cls.createPixMap(value,width,height,dpi)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/sire/users/grg/miniconda3/envs/fabmos/lib/python3.11/site-packages/xmlplot/gui_qt4.py", line 131, in createPixMap
    qImage = QtGui.QImage(stringBuffer, width, height, QtGui.QImage.Format_ARGB32)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: arguments did not match any overloaded call:
  QImage(): too many arguments
  QImage(size: QSize, format: QImage.Format): argument 1 has unexpected type 'memoryview'
  QImage(width: int, height: int, format: QImage.Format): argument 1 has unexpected type 'memoryview'
  QImage(data: typing.Optional[bytes], width: int, height: int, format: QImage.Format): argument 2 has unexpected type 'float'
  QImage(data: typing.Optional[PyQt5.sip.voidptr], width: int, height: int, format: QImage.Format): argument 2 has unexpected type 'float'
  QImage(data: typing.Optional[bytes], width: int, height: int, bytesPerLine: int, format: QImage.Format): argument 2 has unexpected type 'float'
  QImage(data: typing.Optional[PyQt5.sip.voidptr], width: int, height: int, bytesPerLine: int, format: QImage.Format): argument 2 has unexpected type 'float'
  QImage(xpm: List[str]): argument 1 has unexpected type 'memoryview'
  QImage(fileName: str, format: typing.Optional[str] = None): argument 1 has unexpected type 'memoryview'
  QImage(a0: QImage): argument 1 has unexpected type 'memoryview'
  QImage(variant: Any): too many arguments

**Comment by jornbr** [comment]
This is now, finally, fixed in version 0.99.42. Thanks for reporting!
