### ISSUE TITLE
Opening Settings menu/Figure Properties triggers error. Change of colomap doesn't work

### ISSUE THREAD

**Issue by JohannesTimm** [BoldingBruggeman/pyncview#15]
Setup : Miniconda Setup from AMEMR Workshop
System : Ubuntu 22.04.4

Traceback (most recent call last):
  File "/home/johannes/miniconda3/envs/amemr/lib/python3.12/site-packages/xmlstore/gui_qt4.py", line 910, in paint
    editorclass.displayValue(self,painter,option,index)
  File "/home/johannes/miniconda3/envs/amemr/lib/python3.12/site-packages/xmlstore/gui_qt4.py", line 839, in displayValue
    qPixMap = cls.getPixMap(value,cls.width,cls.height,dpi)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/johannes/miniconda3/envs/amemr/lib/python3.12/site-packages/xmlstore/gui_qt4.py", line 825, in getPixMap
    qPixMap = cls.createPixMap(value,width,height,dpi)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/johannes/miniconda3/envs/amemr/lib/python3.12/site-packages/xmlplot/gui_qt4.py", line 131, in createPixMap
    qImage = QtGui.QImage(stringBuffer, width, height, QtGui.QImage.Format_ARGB32)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: arguments did not match any overloaded call:
  QImage(): too many arguments
  QImage(size: QSize, format: QImage.Format): argument 1 has unexpected type 'memoryview'
  QImage(width: int, height: int, format: QImage.Format): argument 1 has unexpected type 'memoryview'
  QImage(data: typing.Optional[bytes], width: int, height: int, format: QImage.Format): argument 2 has unexpected type 'float'
  QImage(data: typing.Optional[PyQt5.sip.voidptr], width: int, height: int, format: QImage.Format): argument 2 has unexpected type 'float'
  QImage(data: typing.Optional[bytes], width: int, height: int, bytesPerLine: int, format: QImage.Format): argument 2 has unexpected type 'float'
  QImage(data: typing.Optional[PyQt5.sip.voidptr], width: int, height: int, bytesPerLine: int, format: QImage.Format): argument 2 has unexpected type 'float'
  QImage(xpm: List[str]): argument 1 has unexpected type 'memoryview'
  QImage(fileName: str, format: typing.Optional[str] = None): argument 1 has unexpected type 'memoryview'
  QImage(a0: QImage): argument 1 has unexpected type 'memoryview'
  QImage(variant: Any): too many arguments
Traceback (most recent call last):
  File "/home/johannes/miniconda3/envs/amemr/lib/python3.12/site-packages/xmlstore/gui_qt4.py", line 910, in paint
    editorclass.displayValue(self,painter,option,index)
  File "/home/johannes/miniconda3/envs/amemr/lib/python3.12/site-packages/xmlstore/gui_qt4.py", line 839, in displayValue
    qPixMap = cls.getPixMap(value,cls.width,cls.height,dpi)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/johannes/miniconda3/envs/amemr/lib/python3.12/site-packages/xmlstore/gui_qt4.py", line 825, in getPixMap
    qPixMap = cls.createPixMap(value,width,height,dpi)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/johannes/miniconda3/envs/amemr/lib/python3.12/site-packages/xmlplot/gui_qt4.py", line 131, in createPixMap
    qImage = QtGui.QImage(stringBuffer, width, height, QtGui.QImage.Format_ARGB32)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: arguments did not match any overloaded call:
  QImage(): too many arguments
  QImage(size: QSize, format: QImage.Format): argument 1 has unexpected type 'memoryview'
  QImage(width: int, height: int, format: QImage.Format): argument 1 has unexpected type 'memoryview'
  QImage(data: typing.Optional[bytes], width: int, height: int, format: QImage.Format): argument 2 has unexpected type 'float'
  QImage(data: typing.Optional[PyQt5.sip.voidptr], width: int, height: int, format: QImage.Format): argument 2 has unexpected type 'float'
  QImage(data: typing.Optional[bytes], width: int, height: int, bytesPerLine: int, format: QImage.Format): argument 2 has unexpected type 'float'
  QImage(data: typing.Optional[PyQt5.sip.voidptr], width: int, height: int, bytesPerLine: int, format: QImage.Format): argument 2 has unexpected type 'float'
  QImage(xpm: List[str]): argument 1 has unexpected type 'memoryview'
  QImage(fileName: str, format: typing.Optional[str] = None): argument 1 has unexpected type 'memoryview'
  QImage(a0: QImage): argument 1 has unexpected type 'memoryview'
  QImage(variant: Any): too many arguments
Traceback (most recent call last):
  File "/home/johannes/miniconda3/envs/amemr/lib/python3.12/site-packages/xmlstore/gui_qt4.py", line 910, in paint
    editorclass.displayValue(self,painter,option,index)
  File "/home/johannes/miniconda3/envs/amemr/lib/python3.12/site-packages/xmlstore/gui_qt4.py", line 839, in displayValue
    qPixMap = cls.getPixMap(value,cls.width,cls.height,dpi)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/johannes/miniconda3/envs/amemr/lib/python3.12/site-packages/xmlstore/gui_qt4.py", line 825, in getPixMap
    qPixMap = cls.createPixMap(value,width,height,dpi)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/johannes/miniconda3/envs/amemr/lib/python3.12/site-packages/xmlplot/gui_qt4.py", line 131, in createPixMap
    qImage = QtGui.QImage(stringBuffer, width, height, QtGui.QImage.Format_ARGB32)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: arguments did not match any overloaded call:
  QImage(): too many arguments
  QImage(size: QSize, format: QImage.Format): argument 1 has unexpected type 'memoryview'
  QImage(width: int, height: int, format: QImage.Format): argument 1 has unexpected type 'memoryview'
  QImage(data: typing.Optional[bytes], width: int, height: int, format: QImage.Format): argument 2 has unexpected type 'float'
  QImage(data: typing.Optional[PyQt5.sip.voidptr], width: int, height: int, format: QImage.Format): argument 2 has unexpected type 'float'
  QImage(data: typing.Optional[bytes], width: int, height: int, bytesPerLine: int, format: QImage.Format): argument 2 has unexpected type 'float'
  QImage(data: typing.Optional[PyQt5.sip.voidptr], width: int, height: int, bytesPerLine: int, format: QImage.Format): argument 2 has unexpected type 'float'
  QImage(xpm: List[str]): argument 1 has unexpected type 'memoryview'
  QImage(fileName: str, format: typing.Optional[str] = None): argument 1 has unexpected type 'memoryview'
  QImage(a0: QImage): argument 1 has unexpected type 'memoryview'
  QImage(variant: Any): too many arguments
Traceback (most recent call last):
  File "/home/johannes/miniconda3/envs/amemr/lib/python3.12/site-packages/xmlstore/gui_qt4.py", line 910, in paint
    editorclass.displayValue(self,painter,option,index)
  File "/home/johannes/miniconda3/envs/amemr/lib/python3.12/site-packages/xmlstore/gui_qt4.py", line 839, in displayValue
    qPixMap = cls.getPixMap(value,cls.width,cls.height,dpi)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/johannes/miniconda3/envs/amemr/lib/python3.12/site-packages/xmlstore/gui_qt4.py", line 825, in getPixMap
    qPixMap = cls.createPixMap(value,width,height,dpi)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/johannes/miniconda3/envs/amemr/lib/python3.12/site-packages/xmlplot/gui_qt4.py", line 131, in createPixMap
    qImage = QtGui.QImage(stringBuffer, width, height, QtGui.QImage.Format_ARGB32)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: arguments did not match any overloaded call:
  QImage(): too many arguments
  QImage(size: QSize, format: QImage.Format): argument 1 has unexpected type 'memoryview'
  QImage(width: int, height: int, format: QImage.Format): argument 1 has unexpected type 'memoryview'
  QImage(data: typing.Optional[bytes], width: int, height: int, format: QImage.Format): argument 2 has unexpected type 'float'
  QImage(data: typing.Optional[PyQt5.sip.voidptr], width: int, height: int, format: QImage.Format): argument 2 has unexpected type 'float'
  QImage(data: typing.Optional[bytes], width: int, height: int, bytesPerLine: int, format: QImage.Format): argument 2 has unexpected type 'float'
  QImage(data: typing.Optional[PyQt5.sip.voidptr], width: int, height: int, bytesPerLine: int, format: QImage.Format): argument 2 has unexpected type 'float'
  QImage(xpm: List[str]): argument 1 has unexpected type 'memoryview'
  QImage(fileName: str, format: typing.Optional[str] = None): argument 1 has unexpected type 'memoryview'
  QImage(a0: QImage): argument 1 has unexpected type 'memoryview'
  QImage(variant: Any): too many arguments
Traceback (most recent call last):
  File "/home/johannes/miniconda3/envs/amemr/lib/python3.12/site-packages/xmlstore/gui_qt4.py", line 882, in createEditor
    editor = createEditor(node,parent,**self.properties)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/johannes/miniconda3/envs/amemr/lib/python3.12/site-packages/xmlstore/gui_qt4.py", line 90, in createEditor
    editor = editorclass(parent,node,**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/johannes/miniconda3/envs/amemr/lib/python3.12/site-packages/xmlplot/gui_qt4.py", line 109, in __init__
    xmlstore.gui_qt4.StringWithImageEditor.__init__(self,parent,node,items,**kwargs)
  File "/home/johannes/miniconda3/envs/amemr/lib/python3.12/site-packages/xmlstore/gui_qt4.py", line 808, in __init__
    self.setIconSize(QtCore.QSize(self.width,self.height))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: arguments did not match any overloaded call:
  QSize(): too many arguments
  QSize(w: int, h: int): argument 1 has unexpected type 'float'
  QSize(a0: QSize): argument 1 has unexpected type 'float'
Traceback (most recent call last):
  File "/home/johannes/miniconda3/envs/amemr/lib/python3.12/site-packages/xmlstore/gui_qt4.py", line 910, in paint
    editorclass.displayValue(self,painter,option,index)
  File "/home/johannes/miniconda3/envs/amemr/lib/python3.12/site-packages/xmlstore/gui_qt4.py", line 839, in displayValue
    qPixMap = cls.getPixMap(value,cls.width,cls.height,dpi)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/johannes/miniconda3/envs/amemr/lib/python3.12/site-packages/xmlstore/gui_qt4.py", line 825, in getPixMap
    qPixMap = cls.createPixMap(value,width,height,dpi)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/johannes/miniconda3/envs/amemr/lib/python3.12/site-packages/xmlplot/gui_qt4.py", line 131, in createPixMap
    qImage = QtGui.QImage(stringBuffer, width, height, QtGui.QImage.Format_ARGB32)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: arguments did not match any overloaded call:
  QImage(): too many arguments
  QImage(size: QSize, format: QImage.Format): argument 1 has unexpected type 'memoryview'
  QImage(width: int, height: int, format: QImage.Format): argument 1 has unexpected type 'memoryview'
  QImage(data: typing.Optional[bytes], width: int, height: int, format: QImage.Format): argument 2 has unexpected type 'float'
  QImage(data: typing.Optional[PyQt5.sip.voidptr], width: int, height: int, format: QImage.Format): argument 2 has unexpected type 'float'
  QImage(data: typing.Optional[bytes], width: int, height: int, bytesPerLine: int, format: QImage.Format): argument 2 has unexpected type 'float'
  QImage(data: typing.Optional[PyQt5.sip.voidptr], width: int, height: int, bytesPerLine: int, format: QImage.Format): argument 2 has unexpected type 'float'
  QImage(xpm: List[str]): argument 1 has unexpected type 'memoryview'
  QImage(fileName: str, format: typing.Optional[str] = None): argument 1 has unexpected type 'memoryview'
  QImage(a0: QImage): argument 1 has unexpected type 'memoryview'
  QImage(variant: Any): too many arguments
Traceback (most recent call last):
  File "/home/johannes/miniconda3/envs/amemr/lib/python3.12/site-packages/xmlstore/gui_qt4.py", line 910, in paint
    editorclass.displayValue(self,painter,option,index)
  File "/home/johannes/miniconda3/envs/amemr/lib/python3.12/site-packages/xmlstore/gui_qt4.py", line 839, in displayValue
    qPixMap = cls.getPixMap(value,cls.width,cls.height,dpi)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/johannes/miniconda3/envs/amemr/lib/python3.12/site-packages/xmlstore/gui_qt4.py", line 825, in getPixMap
    qPixMap = cls.createPixMap(value,width,height,dpi)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/johannes/miniconda3/envs/amemr/lib/python3.12/site-packages/xmlplot/gui_qt4.py", line 131, in createPixMap
    qImage = QtGui.QImage(stringBuffer, width, height, QtGui.QImage.Format_ARGB32)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: arguments did not match any overloaded call:
  QImage(): too many arguments
  QImage(size: QSize, format: QImage.Format): argument 1 has unexpected type 'memoryview'
  QImage(width: int, height: int, format: QImage.Format): argument 1 has unexpected type 'memoryview'
  QImage(data: typing.Optional[bytes], width: int, height: int, format: QImage.Format): argument 2 has unexpected type 'float'
  QImage(data: typing.Optional[PyQt5.sip.voidptr], width: int, height: int, format: QImage.Format): argument 2 has unexpected type 'float'
  QImage(data: typing.Optional[bytes], width: int, height: int, bytesPerLine: int, format: QImage.Format): argument 2 has unexpected type 'float'
  QImage(data: typing.Optional[PyQt5.sip.voidptr], width: int, height: int, bytesPerLine: int, format: QImage.Format): argument 2 has unexpected type 'float'
  QImage(xpm: List[str]): argument 1 has unexpected type 'memoryview'
  QImage(fileName: str, format: typing.Optional[str] = None): argument 1 has unexpected type 'memoryview'
  QImage(a0: QImage): argument 1 has unexpected type 'memoryview'
  QImage(variant: Any): too many arguments
Traceback (most recent call last):
  File "/home/johannes/miniconda3/envs/amemr/lib/python3.12/site-packages/xmlstore/gui_qt4.py", line 910, in paint
    editorclass.displayValue(self,painter,option,index)
  File "/home/johannes/miniconda3/envs/amemr/lib/python3.12/site-packages/xmlstore/gui_qt4.py", line 839, in displayValue
    qPixMap = cls.getPixMap(value,cls.width,cls.height,dpi)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/johannes/miniconda3/envs/amemr/lib/python3.12/site-packages/xmlstore/gui_qt4.py", line 825, in getPixMap
    qPixMap = cls.createPixMap(value,width,height,dpi)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/johannes/miniconda3/envs/amemr/lib/python3.12/site-packages/xmlplot/gui_qt4.py", line 131, in createPixMap
    qImage = QtGui.QImage(stringBuffer, width, height, QtGui.QImage.Format_ARGB32)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: arguments did not match any overloaded call:
  QImage(): too many arguments
  QImage(size: QSize, format: QImage.Format): argument 1 has unexpected type 'memoryview'
  QImage(width: int, height: int, format: QImage.Format): argument 1 has unexpected type 'memoryview'
  QImage(data: typing.Optional[bytes], width: int, height: int, format: QImage.Format): argument 2 has unexpected type 'float'
  QImage(data: typing.Optional[PyQt5.sip.voidptr], width: int, height: int, format: QImage.Format): argument 2 has unexpected type 'float'
  QImage(data: typing.Optional[bytes], width: int, height: int, bytesPerLine: int, format: QImage.Format): argument 2 has unexpected type 'float'
  QImage(data: typing.Optional[PyQt5.sip.voidptr], width: int, height: int, bytesPerLine: int, format: QImage.Format): argument 2 has unexpected type 'float'
  QImage(xpm: List[str]): argument 1 has unexpected type 'memoryview'
  QImage(fileName: str, format: typing.Optional[str] = None): argument 1 has unexpected type 'memoryview'
  QImage(a0: QImage): argument 1 has unexpected type 'memoryview'
  QImage(variant: Any): too many arguments
Traceback (most recent call last):
  File "/home/johannes/miniconda3/envs/amemr/lib/python3.12/site-packages/xmlstore/gui_qt4.py", line 910, in paint
    editorclass.displayValue(self,painter,option,index)
  File "/home/johannes/miniconda3/envs/amemr/lib/python3.12/site-packages/xmlstore/gui_qt4.py", line 839, in displayValue
    qPixMap = cls.getPixMap(value,cls.width,cls.height,dpi)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/johannes/miniconda3/envs/amemr/lib/python3.12/site-packages/xmlstore/gui_qt4.py", line 825, in getPixMap
    qPixMap = cls.createPixMap(value,width,height,dpi)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/johannes/miniconda3/envs/amemr/lib/python3.12/site-packages/xmlplot/gui_qt4.py", line 131, in createPixMap
    qImage = QtGui.QImage(stringBuffer, width, height, QtGui.QImage.Format_ARGB32)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: arguments did not match any overloaded call:
  QImage(): too many arguments
  QImage(size: QSize, format: QImage.Format): argument 1 has unexpected type 'memoryview'
  QImage(width: int, height: int, format: QImage.Format): argument 1 has unexpected type 'memoryview'
  QImage(data: typing.Optional[bytes], width: int, height: int, format: QImage.Format): argument 2 has unexpected type 'float'
  QImage(data: typing.Optional[PyQt5.sip.voidptr], width: int, height: int, format: QImage.Format): argument 2 has unexpected type 'float'
  QImage(data: typing.Optional[bytes], width: int, height: int, bytesPerLine: int, format: QImage.Format): argument 2 has unexpected type 'float'
  QImage(data: typing.Optional[PyQt5.sip.voidptr], width: int, height: int, bytesPerLine: int, format: QImage.Format): argument 2 has unexpected type 'float'
  QImage(xpm: List[str]): argument 1 has unexpected type 'memoryview'
  QImage(fileName: str, format: typing.Optional[str] = None): argument 1 has unexpected type 'memoryview'
  QImage(a0: QImage): argument 1 has unexpected type 'memoryview'
  QImage(variant: Any): too many arguments
Traceback (most recent call last):
  File "/home/johannes/miniconda3/envs/amemr/lib/python3.12/site-packages/xmlstore/gui_qt4.py", line 910, in paint
    editorclass.displayValue(self,painter,option,index)
  File "/home/johannes/miniconda3/envs/amemr/lib/python3.12/site-packages/xmlstore/gui_qt4.py", line 839, in displayValue
    qPixMap = cls.getPixMap(value,cls.width,cls.height,dpi)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/johannes/miniconda3/envs/amemr/lib/python3.12/site-packages/xmlstore/gui_qt4.py", line 825, in getPixMap
    qPixMap = cls.createPixMap(value,width,height,dpi)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/johannes/miniconda3/envs/amemr/lib/python3.12/site-packages/xmlplot/gui_qt4.py", line 131, in createPixMap
    qImage = QtGui.QImage(stringBuffer, width, height, QtGui.QImage.Format_ARGB32)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: arguments did not match any overloaded call:
  QImage(): too many arguments
  QImage(size: QSize, format: QImage.Format): argument 1 has unexpected type 'memoryview'
  QImage(width: int, height: int, format: QImage.Format): argument 1 has unexpected type 'memoryview'
  QImage(data: typing.Optional[bytes], width: int, height: int, format: QImage.Format): argument 2 has unexpected type 'float'
  QImage(data: typing.Optional[PyQt5.sip.voidptr], width: int, height: int, format: QImage.Format): argument 2 has unexpected type 'float'
  QImage(data: typing.Optional[bytes], width: int, height: int, bytesPerLine: int, format: QImage.Format): argument 2 has unexpected type 'float'
  QImage(data: typing.Optional[PyQt5.sip.voidptr], width: int, height: int, bytesPerLine: int, format: QImage.Format): argument 2 has unexpected type 'float'
  QImage(xpm: List[str]): argument 1 has unexpected type 'memoryview'
  QImage(fileName: str, format: typing.Optional[str] = None): argument 1 has unexpected type 'memoryview'
  QImage(a0: QImage): argument 1 has unexpected type 'memoryview'
  QImage(variant: Any): too many arguments

**Comment by jornbr** [comment]
This is now, finally, fixed in version 0.99.42. Thanks for reporting!
