### ISSUE TITLE
Properties tab issue

### ISSUE THREAD

**Issue by tmshanahan** [BoldingBruggeman/pyncview#6]
Trying out pyncview I got the following error when using the "properties" tab:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/pncview/lib/python3.11/site-packages/xmlplot/gui_qt4.py", line 562, in onAdvancedClicked
    self.dialogAdvanced.resizeColumns()
  File "/opt/anaconda3/envs/pncview/lib/python3.11/site-packages/xmlstore/gui_qt4.py", line 1772, in resizeColumns
    if self.tree.columnWidth(0)>maxwidth: self.tree.setColumnWidth(0,maxwidth)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: setColumnWidth(self, column: int, width: int): argument 2 has unexpected type 'float'

**Comment by jornbr** [comment]
This should now be fixed in version 0.99.33.

To upgrade, use `pip install pyncview --upgrade`
